services:
  mongodb:
    image: mongo:latest
    container_name: local-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: ecommerce_db
    volumes:
      - mongo_data:/data/db

  hbase:
    image: harisekhon/hbase:latest
    container_name: local-hbase
    restart: unless-stopped
    ports:
      - "9090:9090"    # HBase Thrift Port (Required by HappyBase)
      - "16010:16010"  # HBase Web UI
      - "2181:2181"    # Zookeeper Port
    volumes:
      - hbase_data:/data

volumes:
  mongo_data:
    driver: local
  hbase_data:
    driver: local
